# permissions for end users to edit helmchartproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmchartproxy-editor-role
rules:
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - helmchartproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - helmchartproxies/status
  verbs:
  - get
