# The following patch adds the `clusterctl.cluster.x-k8s.io/move-hierarchy` label to the HelmChartProxy CRD type.
# Note that this label will be present on the HelmChartProxy kind, not HelmChartProxy objects themselves.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: helmchartproxies.addons.cluster.x-k8s.io
