name: scan-images

on:
  schedule:
    - cron: "0 12 * * 1"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  scan:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # tag=v3.1.0
    - name: Setup go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # tag=v5.0.0
      with:
        go-version: 1.21
    - name: Run verify container script
      run: make verify-container-images
